In [1]:
import pandas as pd

In [4]:
txt_file = r"./logit_idea/data/ncvoter_Statewide.txt"
csv_file = r"./logit_idea/data/ncvoter_Statewide.csv"

df = pd.read_csv(txt_file, delimiter = "\t")

/Users/sahluwalia/acre/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3257: DtypeWarning: Columns (23,34,35,36,37,38,39,41,42,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,65,66) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
df.columns

Index(['county_id', 'county_desc', 'voter_reg_num', 'ncid', 'last_name',
       'first_name', 'middle_name', 'name_suffix_lbl', 'status_cd',
       'voter_status_desc', 'reason_cd', 'voter_status_reason_desc',
       'res_street_address', 'res_city_desc', 'state_cd', 'zip_code',
       'mail_addr1', 'mail_addr2', 'mail_addr3', 'mail_addr4', 'mail_city',
       'mail_state', 'mail_zipcode', 'full_phone_number', 'confidential_ind',
       'registr_dt', 'race_code', 'ethnic_code', 'party_cd', 'gender_code',
       'birth_year', 'age_at_year_end', 'birth_state', 'drivers_lic',
       'precinct_abbrv', 'precinct_desc', 'municipality_abbrv',
       'municipality_desc', 'ward_abbrv', 'ward_desc', 'cong_dist_abbrv',
       'super_court_abbrv', 'judic_dist_abbrv', 'nc_senate_abbrv',
       'nc_house_abbrv', 'county_commiss_abbrv', 'county_commiss_desc',
       'township_abbrv', 'township_desc', 'school_dist_abbrv',
       'school_dist_desc', 'fire_dist_abbrv', 'fire_dist_desc',
       'water_dist_abbrv', 'water_dist_desc', 'sewer_dist_abbrv',
       'sewer_dist_desc', 'sanit_dist_abbrv', 'sanit_dist_desc',
       'rescue_dist_abbrv', 'rescue_dist_desc', 'munic_dist_abbrv',
       'munic_dist_desc', 'dist_1_abbrv', 'dist_1_desc', 'vtd_abbrv',
       'vtd_desc'],
      dtype='object')

In [22]:
clean = df.dropna(subset = ['zip_code'])
exclude = ['RD','R2','DI'] #removing certain non-applicable voter types (e.g. deceased)
clean = clean[~clean['reason_cd'].isin(exclude)][['zip_code','race_code','party_cd',
      'first_name', 'middle_name',    'last_name',                                                    
        'gender_code', 'ethnic_code', "birth_year", 'registr_dt',
         'res_street_address', 'res_city_desc', 'state_cd', 'zip_code',
       'mail_addr1', 'mail_addr2', 'mail_addr3', 'mail_addr4', 'mail_city',
       'mail_state', 'mail_zipcode',     'precinct_abbrv', 'precinct_desc', 'municipality_abbrv',
       'municipality_desc', 'ward_abbrv', 'ward_desc', 'cong_dist_abbrv',
       'super_court_abbrv', 'judic_dist_abbrv', 'nc_senate_abbrv',
       'nc_house_abbrv',                                             ]]

In [23]:
clean.head()

,zip_code,race_code,party_cd,first_name,middle_name,last_name,gender_code,ethnic_code,birth_year,registr_dt,...,precinct_desc,municipality_abbrv,municipality_desc,ward_abbrv,ward_desc,cong_dist_abbrv,super_court_abbrv,judic_dist_abbrv,nc_senate_abbrv,nc_house_abbrv
0,27253.0,W,UNA,RUTH,EVELYN,AABEL,F,NL,1935,10/01/1984,...,NORTH NEWLIN,NaN,NaN,NaN,NaN,4.0,15A,15A,25.0,64.0
2,27302.0,W,REP,TIMOTHY,DUANE,AARMSTRONG,M,UN,1966,10/31/2020,...,MELVILLE 3,NaN,NaN,NaN,NaN,4.0,15A,15A,25.0,63.0
3,27215.0,W,UNA,CHRISTINA,CASTAGNA,AARON,F,UN,1976,03/26/1996,...,SOUTH BOONE,BUR,BURLINGTON,NaN,NaN,4.0,15A,15A,25.0,64.0
4,27215.0,W,UNA,CLAUDIA,HAYDEN,AARON,F,NL,1945,08/15/1989,...,BURLINGTON 4,BUR,BURLINGTON,NaN,NaN,4.0,15A,15A,25.0,63.0
5,27253.0,W,DEM,JAMES,MICHAEL,AARON,M,UN,1948,03/07/2012,...,NORTH NEWLIN,NaN,NaN,NaN,NaN,4.0,15A,15A,25.0,64.0

In [24]:

clean['birth_age'] = 2022 - clean['birth_year'].astype('float64')
clean['registr_dt'] = pd.to_datetime(clean['registr_dt'],yearfirst=True, errors='ignore')

In [26]:
clean.to_csv("./logit_idea/data/voter_records_nc.csv")